// import type { NextPage } from 'next'
import React from 'react'
import Head from 'next/head' 
import AboutPage from '../components/SalesPage/AboutPage'
import AppFeature from '../components/SalesPage/AppFeatures'
import AppStore from '../components/SalesPage/AppStore'
import Footer from '../components/SalesPage/Footer'
import Navbar from '../components/SalesPage/Navbar'   
import SecondFeature from '../components/SalesPage/SecondFeatures'
import ThirdFeatures from '../components/SalesPage/ThirdFeatures'
import Router from 'next/router'

export default function index() { 

  React.useEffect(() => { 
      const token = localStorage.getItem('token')
      if(token ){
          Router.push('/dashboard')
      }
  });
  
  return (
    <div className='w-full h-full overflow-x-hidden ' >
      <Head>
        <title>HX-Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      <div className='w-full h-auto flex flex-col bg-heritagecolor' >  
        <div className='w-full h-auto fixed z-50' >
          <Navbar/>
        </div> 
          <AppFeature /> 
      </div>
      <div  id='feature' className='w-full h-full' >
        <SecondFeature />
      </div>
      <div className='w-full h-full'>
        <ThirdFeatures />
      </div>
      <div id='testimony' className='w-full  pt-16 h-full'>
        <AboutPage />
      </div>
      <div  id='store' className='w-full h-full pt-16 '>
        <AppStore />
      </div>
      <div>
        <Footer />
      </div>
    </div>
    )
}
